### ISSUE TITLE
Why not Rust?

### ISSUE THREAD

**Issue by vikiival** [brano-hozza/advent-of-code-2022#1]
Hello,
I would like to ask if there is a plan to rewrite it into Rust?

<img width="319" alt="Screenshot 2022-12-04 at 13 47 35" src="https://user-images.githubusercontent.com/22471030/205491325-17ef9fde-21ea-48f1-9677-4b152f979482.png">

**Comment by bran0h** [comment]
@vikiival  Actually this morning I was thinking about it 😆

**Comment by bran0h** [comment]
@vikiival Job done 🚀
